name: Build Android and Web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_android_and_web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'  # Update this to the latest version that includes Dart SDK 3.3.0 or higher
        channel: 'stable'
    - name: Check Dart version
      run: dart --version
    - run: flutter pub get
    - run: flutter test
    
    - name: Build Android APK
      run: flutter build apk
    
    - name: Build Web
      run: flutter build web
    
    - name: Upload Android Build
      uses: actions/upload-artifact@v3
      with:
        name: android-release
        path: build/app/outputs/flutter-apk/app-release.apk
    
    - name: Upload Web Build
      uses: actions/upload-artifact@v3
      with:
        name: web-release
        path: build/web
