# .github/workflows/build-and-release.yml
name: Build and Release Flutter App

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*' # Triggers on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build for Android
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --release

      - name: Build for Web
        if: matrix.os == 'ubuntu-latest'
        run: flutter build web --release

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: flutter build macos --release

      - name: Upload Android APK
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Web Build
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web/

      - name: Upload macOS Build
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: build/macos/Build/Products/Release/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download Android APK
        uses: actions/download-artifact@v3
        with:
          name: android-apk
          path: artifacts/android

      - name: Download Web Build
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: artifacts/web

      - name: Download macOS Build
        uses: actions/download-artifact@v3
        with:
          name: macos-build
          path: artifacts/macos

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Android APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/android/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Web Build to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/web/
          asset_name: web-build.zip
          asset_content_type: application/zip

      - name: Upload macOS Build to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/macos/
          asset_name: macos-build.zip
          asset_content_type: application/zip
